[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tomosipo"
version = "0.7.0"
description = "A usable Python astra-based tomography library."
readme = "README.md"
license = {text = "GPL-3.0-only"}
authors = [{name = "Allard Hendriksen", email = "allard.hendriksen@cwi.nl"}]
requires-python = ">=3.11"
dependencies = [
    "astra-toolbox==2.3.1",
    "numpy>=2.2",
    "torch==2.6",
    "pytorch-lightning==2.5"
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GPL-3.0-only",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11"
]

[project.optional-dependencies]
dev = [
    "autopep8",
    "rope",
    "jedi",
    "flake8",
    "importmagic",
    "black",
    "yapf",
    "snakeviz",
    "sphinx",
    "sphinx_rtd_theme",
    "sphinx-autodoc-typehints",
    "recommonmark",
    "watchdog",
    "coverage",
    "pytest",
    "pytest-runner"
]

[tool.flake8]
exclude = ["docs"]
max-line-length = 80
select = ["C", "E", "F", "W", "B", "B950"]
ignore = ["E501"]

[tool.pytest.ini_options]
addopts = "--ignore=setup.py"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')"
]
